imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:
    #esi: ~
    #translator: { fallbacks: ['%locale%'] }
    secret: '%secret%'
    router:
        resource: '%kernel.project_dir%/app/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    translator: { fallback: en }
    validation: { enable_annotations: true }
    serializer: { enable_annotations: true }
    default_locale: '%locale%'
    trusted_hosts: ~
    session:
        # https://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id: session.handler.native_file
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
    fragments: ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true
    templating:
        engines: ['twig']
# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    number_format:
            thousands_separator: '.'

# Doctrine Configuration
doctrine:
    dbal:
        host:     '%database_host%'
        port: 3306
        dbname:   '%database_name%'
        user:     '%database_user%'
        password: '%database_password%'
        charset: UTF8
        #path: '%kernel.project_dir%/app/sqlite.db'
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: '%kernel.project_dir%/var/data/data.sqlite'
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #path: '%database_path%'

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    host: '%mailer_host%'
    username: '%mailer_user%'
    password: '%mailer_password%'
    spool: { type: memory }


fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: AppBundle\Entity\User
    service:                               # this lines
    from_email:
      address: "nesrinesghaier10@gmail.com"
      sender_name: "test"
    registration:
           form:
               type: AppBundle\Form\UserType

fos_rest:
    body_converter:
        enabled: true
        validate: true
    view:
        #formats: { json: true, xml: false, rss: false }
        view_response_listener: true
    serializer:
        serialize_null: true
    routing_loader:
        include_format: false
    body_listener:
            enabled: true
    format_listener:
#        rules:
#        - { path: '^/', priorities: ['json'], fallback_format: 'json' }

sensio_framework_extra:
    view: { annotations: false }
    request: { converters: true }

fos_oauth_server:
    db_driver: orm       # Drivers available: orm, mongodb, or propel
    client_class:        AppBundle\Entity\Authentication\Client
    access_token_class:  AppBundle\Entity\Authentication\AccessToken
    refresh_token_class: AppBundle\Entity\Authentication\RefreshToken
    auth_code_class:     AppBundle\Entity\Authentication\AuthCode
    service:
      user_provider: fos_user.user_provider.username
      options:
        access_token_lifetime: 86400
        refresh_token_lifetime: 1209600
        auth_code_lifetime: 30
      client_manager:         fos_oauth_server.client_manager.default
      access_token_manager:   fos_oauth_server.access_token_manager.default
      refresh_token_manager:  fos_oauth_server.refresh_token_manager.default
      auth_code_manager:      fos_oauth_server.auth_code_manager.default