user_register:
  resource: "@AppBundle/Controller/RegistrationController.php"
  type:     rest

user_login:
  resource: "@AppBundle/Controller/SecurityController.php"
  type:     rest


app_:
    resource: "@AppBundle/Controller/UserController.php"
    type:     rest

form:
    type:     rest
    resource: "@AppBundle/Controller/FormController.php"

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

fos_oauth_server_token:
  resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"

fos_oauth_server_authorize:
  resource: "@FOSOAuthServerBundle/Resources/config/routing/authorize.xml"