app_user:
    resource: "@AppBundle/Controller/UserController.php"
    type:     annotation

app:
    resource: "@AppBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

form:
    type:     rest
    resource: "@AppBundle/Controller/FormController.php"
