# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    encoders:
        AppBundle\Entity\User: bcrypt
    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN
    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username
        in_memory:
            memory: ~
        database_users:
            entity: { class: App\Entity\User, property: email }
    firewalls:
#        oauth_token:
#          pattern:    ^/oauth/v2/token
#          security:   false

#        oauth_authorize:
#          pattern:    ^/oauth/v2/auth
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            form_login:
              provider: fos_userbundle
              csrf_token_generator: security.csrf.token_manager
            logout:
                path: /logout
                target: /logout
                invalidate_session: true
            anonymous: true

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            #form_login: ~
        ###to remove later
        login:
          pattern:  ^/login
          stateless: true
          anonymous: true
          json_login:
            check_path:               /login

        api:
          pattern:   ^/
          fos_oauth:  true
          stateless: true
          anonymous:  false

    access_control:
      - { path: ^/,       roles: IS_AUTHENTICATED_ANONYMOUSLY  }
      - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
      - { path: ^/signup, roles: IS_AUTHENTICATED_ANONYMOUSLY }
      #- { path: ^/,       roles: IS_AUTHENTICATED_FULLY }
