# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    encoders:
        AppBundle\Entity\User: bcrypt
    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN
    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username
        in_memory:
            memory: ~
        database_users:
            entity: { class: App\Entity\User, property: email }
    firewalls:
        api:
          pattern:   ^/api
          fos_oauth:  true
          stateless: true
        oauth_token:
          pattern:    ^/oauth/v2/token
          security:   false
        oauth_authorize:
          pattern:    ^/oauth/v2/auth
          form_login:
            check_path: _security_check
            login_path: _demo_login
          anonymous: true
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            form_login:
              provider: fos_userbundle
              csrf_token_generator: security.csrf.token_manager
            anonymous: true


    access_control:
      #- { path: ^/api, role: IS_AUTHENTICATED_FULLY }
      - { path: ^/signup, roles: IS_AUTHENTICATED_ANONYMOUSLY }
      - { path: ^/signin, roles: IS_AUTHENTICATED_ANONYMOUSLY }
      - { path: ^/oauth/v2/auth$, role: IS_AUTHENTICATED_ANONYMOUSLY }
      #- { path: ^/api, roles: [ IS_AUTHENTICATED_FULLY ] }

