<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMfdeea9\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMfdeea9/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerMfdeea9.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerMfdeea9\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerMfdeea9\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Mfdeea9',
    'container.build_id' => '5ca4ac78',
    'container.build_time' => 1533025353,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerMfdeea9');
